export interface Player {
  id: string;
  fullName: string;
  position: string;
  club: string;
  height: string;
  weight: string;
  strongFoot: string;
  marketValue: string;
  imageUrl: string;
}

export interface Nation {
  id: string;
  name: string;
  code: string;
  flag: string;
  confederation: string;
  totalSquadValue: string;
  players: Player[];
  jerseyColors: {
    primary: string;
    secondary: string;
    accent: string;
  };
}

export const translations: Record<string, Record<string, string>> = {
  en: {
    title: "FIFA World Cup 2026",
    subtitle: "United 2026",
    allNations: "All Nations",
    players: "Players",
    position: "Position",
    club: "Club",
    height: "Height",
    weight: "Weight",
    strongFoot: "Strong Foot",
    marketValue: "Market Value",
    squadValue: "Squad Value",
    back: "Back",
    searchPlaceholder: "Search nations...",
    goalkeeper: "Goalkeeper",
    defender: "Defender",
    midfielder: "Midfielder",
    forward: "Forward",
    left: "Left",
    right: "Right",
    both: "Both",
    language: "Language",
    hosted: "Hosted by",
    mexico: "Mexico",
    usa: "USA",
    canada: "Canada",
  },
  es: {
    title: "Copa Mundial FIFA 2026",
    subtitle: "Unidos 2026",
    allNations: "Todas las Naciones",
    players: "Jugadores",
    position: "Posición",
    club: "Club",
    height: "Altura",
    weight: "Peso",
    strongFoot: "Pie Dominante",
    marketValue: "Valor de Mercado",
    squadValue: "Valor del Plantel",
    back: "Volver",
    searchPlaceholder: "Buscar naciones...",
    goalkeeper: "Portero",
    defender: "Defensor",
    midfielder: "Centrocampista",
    forward: "Delantero",
    left: "Izquierdo",
    right: "Derecho",
    both: "Ambos",
    language: "Idioma",
    hosted: "Organizado por",
    mexico: "México",
    usa: "EE.UU.",
    canada: "Canadá",
  },
  fr: {
    title: "Coupe du Monde FIFA 2026",
    subtitle: "Unis 2026",
    allNations: "Toutes les Nations",
    players: "Joueurs",
    position: "Position",
    club: "Club",
    height: "Taille",
    weight: "Poids",
    strongFoot: "Pied Fort",
    marketValue: "Valeur Marchande",
    squadValue: "Valeur de l'Équipe",
    back: "Retour",
    searchPlaceholder: "Rechercher des nations...",
    goalkeeper: "Gardien",
    defender: "Défenseur",
    midfielder: "Milieu",
    forward: "Attaquant",
    left: "Gauche",
    right: "Droit",
    both: "Les Deux",
    language: "Langue",
    hosted: "Organisé par",
    mexico: "Mexique",
    usa: "États-Unis",
    canada: "Canada",
  },
  de: {
    title: "FIFA Weltmeisterschaft 2026",
    subtitle: "Vereint 2026",
    allNations: "Alle Nationen",
    players: "Spieler",
    position: "Position",
    club: "Verein",
    height: "Größe",
    weight: "Gewicht",
    strongFoot: "Starker Fuß",
    marketValue: "Marktwert",
    squadValue: "Kaderwert",
    back: "Zurück",
    searchPlaceholder: "Nationen suchen...",
    goalkeeper: "Torwart",
    defender: "Verteidiger",
    midfielder: "Mittelfeldspieler",
    forward: "Stürmer",
    left: "Links",
    right: "Rechts",
    both: "Beide",
    language: "Sprache",
    hosted: "Ausgetragen von",
    mexico: "Mexiko",
    usa: "USA",
    canada: "Kanada",
  },
  pt: {
    title: "Copa do Mundo FIFA 2026",
    subtitle: "Unidos 2026",
    allNations: "Todas as Nações",
    players: "Jogadores",
    position: "Posição",
    club: "Clube",
    height: "Altura",
    weight: "Peso",
    strongFoot: "Pé Forte",
    marketValue: "Valor de Mercado",
    squadValue: "Valor do Elenco",
    back: "Voltar",
    searchPlaceholder: "Pesquisar nações...",
    goalkeeper: "Goleiro",
    defender: "Defensor",
    midfielder: "Meio-campista",
    forward: "Atacante",
    left: "Esquerdo",
    right: "Direito",
    both: "Ambos",
    language: "Idioma",
    hosted: "Sediado por",
    mexico: "México",
    usa: "EUA",
    canada: "Canadá",
  },
  ar: {
    title: "كأس العالم فيفا 2026",
    subtitle: "متحدون 2026",
    allNations: "جميع الدول",
    players: "اللاعبون",
    position: "المركز",
    club: "النادي",
    height: "الطول",
    weight: "الوزن",
    strongFoot: "القدم القوية",
    marketValue: "القيمة السوقية",
    squadValue: "قيمة الفريق",
    back: "رجوع",
    searchPlaceholder: "البحث عن الدول...",
    goalkeeper: "حارس مرمى",
    defender: "مدافع",
    midfielder: "لاعب وسط",
    forward: "مهاجم",
    left: "يسار",
    right: "يمين",
    both: "كلاهما",
    language: "اللغة",
    hosted: "يستضيفها",
    mexico: "المكسيك",
    usa: "الولايات المتحدة",
    canada: "كندا",
  },
  zh: {
    title: "2026年国际足联世界杯",
    subtitle: "联合2026",
    allNations: "所有国家",
    players: "球员",
    position: "位置",
    club: "俱乐部",
    height: "身高",
    weight: "体重",
    strongFoot: "惯用脚",
    marketValue: "市场价值",
    squadValue: "阵容价值",
    back: "返回",
    searchPlaceholder: "搜索国家...",
    goalkeeper: "守门员",
    defender: "后卫",
    midfielder: "中场",
    forward: "前锋",
    left: "左脚",
    right: "右脚",
    both: "双脚",
    language: "语言",
    hosted: "主办方",
    mexico: "墨西哥",
    usa: "美国",
    canada: "加拿大",
  },
  ja: {
    title: "FIFAワールドカップ2026",
    subtitle: "ユナイテッド2026",
    allNations: "全ての国",
    players: "選手",
    position: "ポジション",
    club: "クラブ",
    height: "身長",
    weight: "体重",
    strongFoot: "利き足",
    marketValue: "市場価値",
    squadValue: "チーム価値",
    back: "戻る",
    searchPlaceholder: "国を検索...",
    goalkeeper: "ゴールキーパー",
    defender: "ディフェンダー",
    midfielder: "ミッドフィールダー",
    forward: "フォワード",
    left: "左",
    right: "右",
    both: "両足",
    language: "言語",
    hosted: "開催国",
    mexico: "メキシコ",
    usa: "アメリカ",
    canada: "カナダ",
  },
};

// Generate players for each nation with realistic data
function generatePlayers(nationId: string, nationName: string): Player[] {
  const positions = ["Goalkeeper", "Defender", "Defender", "Defender", "Defender", "Midfielder", "Midfielder", "Midfielder", "Midfielder", "Forward", "Forward", "Forward", "Goalkeeper", "Defender", "Defender", "Midfielder", "Midfielder", "Forward", "Defender", "Midfielder", "Forward", "Goalkeeper", "Defender", "Midfielder", "Forward", "Forward"];
  
  const playersByNation: Record<string, { name: string; club: string; value: string }[]> = {
    argentina: [
      { name: "Emiliano Martínez", club: "Aston Villa", value: "€35M" },
      { name: "Cristian Romero", club: "Tottenham", value: "€60M" },
      { name: "Nicolás Otamendi", club: "Benfica", value: "€5M" },
      { name: "Lisandro Martínez", club: "Manchester United", value: "€55M" },
      { name: "Nahuel Molina", club: "Atlético Madrid", value: "€25M" },
      { name: "Rodrigo De Paul", club: "Atlético Madrid", value: "€30M" },
      { name: "Enzo Fernández", club: "Chelsea", value: "€85M" },
      { name: "Alexis Mac Allister", club: "Liverpool", value: "€75M" },
      { name: "Giovani Lo Celso", club: "Real Betis", value: "€18M" },
      { name: "Lionel Messi", club: "Inter Miami", value: "€30M" },
      { name: "Julián Álvarez", club: "Atlético Madrid", value: "€90M" },
      { name: "Lautaro Martínez", club: "Inter Milan", value: "€85M" },
      { name: "Gerónimo Rulli", club: "Marseille", value: "€8M" },
      { name: "Gonzalo Montiel", club: "Sevilla", value: "€10M" },
      { name: "Nicolás Tagliafico", club: "Lyon", value: "€8M" },
      { name: "Leandro Paredes", club: "Roma", value: "€10M" },
      { name: "Exequiel Palacios", club: "Bayer Leverkusen", value: "€35M" },
      { name: "Alejandro Garnacho", club: "Manchester United", value: "€55M" },
      { name: "Marcos Acuña", club: "Sevilla", value: "€8M" },
      { name: "Guido Rodríguez", club: "West Ham", value: "€15M" },
      { name: "Thiago Almada", club: "Botafogo", value: "€25M" },
      { name: "Franco Armani", club: "River Plate", value: "€2M" },
      { name: "Leonardo Balerdi", club: "Marseille", value: "€25M" },
      { name: "Ángel Di María", club: "Benfica", value: "€8M" },
      { name: "Valentín Castellanos", club: "Lazio", value: "€20M" },
      { name: "Paulo Dybala", club: "Roma", value: "€25M" },
    ],
    brazil: [
      { name: "Alisson Becker", club: "Liverpool", value: "€40M" },
      { name: "Marquinhos", club: "PSG", value: "€50M" },
      { name: "Éder Militão", club: "Real Madrid", value: "€65M" },
      { name: "Gabriel Magalhães", club: "Arsenal", value: "€70M" },
      { name: "Danilo", club: "Juventus", value: "€5M" },
      { name: "Casemiro", club: "Manchester United", value: "€25M" },
      { name: "Bruno Guimarães", club: "Newcastle", value: "€80M" },
      { name: "Lucas Paquetá", club: "West Ham", value: "€55M" },
      { name: "Rodrygo", club: "Real Madrid", value: "€110M" },
      { name: "Vinícius Júnior", club: "Real Madrid", value: "€180M" },
      { name: "Endrick", club: "Real Madrid", value: "€60M" },
      { name: "Richarlison", club: "Tottenham", value: "€40M" },
      { name: "Ederson", club: "Manchester City", value: "€35M" },
      { name: "Guilherme Arana", club: "Atlético Mineiro", value: "€10M" },
      { name: "Wendell", club: "São Paulo", value: "€3M" },
      { name: "João Gomes", club: "Wolves", value: "€35M" },
      { name: "Andreas Pereira", club: "Fulham", value: "€18M" },
      { name: "Raphinha", club: "Barcelona", value: "€65M" },
      { name: "Bremer", club: "Juventus", value: "€45M" },
      { name: "Danilo", club: "Nottingham Forest", value: "€25M" },
      { name: "Savinho", club: "Manchester City", value: "€70M" },
      { name: "Bento", club: "Athletico Paranaense", value: "€12M" },
      { name: "Yan Couto", club: "Borussia Dortmund", value: "€30M" },
      { name: "Estevão", club: "Chelsea", value: "€50M" },
      { name: "Gabriel Martinelli", club: "Arsenal", value: "€75M" },
      { name: "Igor Jesus", club: "Botafogo", value: "€15M" },
    ],
    france: [
      { name: "Mike Maignan", club: "AC Milan", value: "€40M" },
      { name: "Dayot Upamecano", club: "Bayern Munich", value: "€45M" },
      { name: "William Saliba", club: "Arsenal", value: "€90M" },
      { name: "Ibrahima Konaté", club: "Liverpool", value: "€55M" },
      { name: "Theo Hernández", club: "AC Milan", value: "€60M" },
      { name: "Aurélien Tchouaméni", club: "Real Madrid", value: "€85M" },
      { name: "N'Golo Kanté", club: "Al-Ittihad", value: "€15M" },
      { name: "Eduardo Camavinga", club: "Real Madrid", value: "€80M" },
      { name: "Antoine Griezmann", club: "Atlético Madrid", value: "€30M" },
      { name: "Kylian Mbappé", club: "Real Madrid", value: "€180M" },
      { name: "Ousmane Dembélé", club: "PSG", value: "€60M" },
      { name: "Marcus Thuram", club: "Inter Milan", value: "€65M" },
      { name: "Alphonse Areola", club: "West Ham", value: "€8M" },
      { name: "Jules Koundé", club: "Barcelona", value: "€60M" },
      { name: "Ferland Mendy", club: "Real Madrid", value: "€30M" },
      { name: "Adrien Rabiot", club: "Marseille", value: "€25M" },
      { name: "Warren Zaïre-Emery", club: "PSG", value: "€60M" },
      { name: "Randal Kolo Muani", club: "PSG", value: "€45M" },
      { name: "Benjamin Pavard", club: "Inter Milan", value: "€25M" },
      { name: "Youssouf Fofana", club: "AC Milan", value: "€30M" },
      { name: "Bradley Barcola", club: "PSG", value: "€70M" },
      { name: "Brice Samba", club: "Lens", value: "€10M" },
      { name: "Wesley Fofana", club: "Chelsea", value: "€40M" },
      { name: "Khéphren Thuram", club: "Juventus", value: "€35M" },
      { name: "Olivier Giroud", club: "LAFC", value: "€3M" },
      { name: "Christopher Nkunku", club: "Chelsea", value: "€60M" },
    ],
    england: [
      { name: "Jordan Pickford", club: "Everton", value: "€28M" },
      { name: "John Stones", club: "Manchester City", value: "€35M" },
      { name: "Harry Maguire", club: "Manchester United", value: "€20M" },
      { name: "Marc Guéhi", club: "Crystal Palace", value: "€50M" },
      { name: "Kyle Walker", club: "Manchester City", value: "€15M" },
      { name: "Declan Rice", club: "Arsenal", value: "€100M" },
      { name: "Kobbie Mainoo", club: "Manchester United", value: "€60M" },
      { name: "Jude Bellingham", club: "Real Madrid", value: "€150M" },
      { name: "Phil Foden", club: "Manchester City", value: "€130M" },
      { name: "Harry Kane", club: "Bayern Munich", value: "€80M" },
      { name: "Bukayo Saka", club: "Arsenal", value: "€130M" },
      { name: "Cole Palmer", club: "Chelsea", value: "€110M" },
      { name: "Aaron Ramsdale", club: "Southampton", value: "€18M" },
      { name: "Trent Alexander-Arnold", club: "Liverpool", value: "€70M" },
      { name: "Kieran Trippier", club: "Newcastle", value: "€15M" },
      { name: "Conor Gallagher", club: "Atlético Madrid", value: "€45M" },
      { name: "Adam Wharton", club: "Crystal Palace", value: "€40M" },
      { name: "Anthony Gordon", club: "Newcastle", value: "€55M" },
      { name: "Levi Colwill", club: "Chelsea", value: "€50M" },
      { name: "Ezri Konsa", club: "Aston Villa", value: "€35M" },
      { name: "Jarrod Bowen", club: "West Ham", value: "€45M" },
      { name: "Dean Henderson", club: "Crystal Palace", value: "€12M" },
      { name: "Rico Lewis", club: "Manchester City", value: "€40M" },
      { name: "Morgan Gibbs-White", club: "Nottingham Forest", value: "€40M" },
      { name: "Ollie Watkins", club: "Aston Villa", value: "€55M" },
      { name: "Ivan Toney", club: "Al-Ahli", value: "€35M" },
    ],
    germany: [
      { name: "Manuel Neuer", club: "Bayern Munich", value: "€8M" },
      { name: "Antonio Rüdiger", club: "Real Madrid", value: "€35M" },
      { name: "Jonathan Tah", club: "Bayer Leverkusen", value: "€35M" },
      { name: "Nico Schlotterbeck", club: "Borussia Dortmund", value: "€40M" },
      { name: "Joshua Kimmich", club: "Bayern Munich", value: "€50M" },
      { name: "Robert Andrich", club: "Bayer Leverkusen", value: "€28M" },
      { name: "Florian Wirtz", club: "Bayer Leverkusen", value: "€150M" },
      { name: "Jamal Musiala", club: "Bayern Munich", value: "€150M" },
      { name: "Leroy Sané", club: "Bayern Munich", value: "€50M" },
      { name: "Kai Havertz", club: "Arsenal", value: "€65M" },
      { name: "Niclas Füllkrug", club: "West Ham", value: "€25M" },
      { name: "Serge Gnabry", club: "Bayern Munich", value: "€40M" },
      { name: "Marc-André ter Stegen", club: "Barcelona", value: "€25M" },
      { name: "Benjamin Henrichs", club: "RB Leipzig", value: "€12M" },
      { name: "David Raum", club: "RB Leipzig", value: "€20M" },
      { name: "Pascal Groß", club: "Borussia Dortmund", value: "€8M" },
      { name: "Chris Führich", club: "Stuttgart", value: "€22M" },
      { name: "Deniz Undav", club: "Stuttgart", value: "€25M" },
      { name: "Waldemar Anton", club: "Borussia Dortmund", value: "€28M" },
      { name: "Aleksandar Pavlović", club: "Bayern Munich", value: "€35M" },
      { name: "Maximilian Beier", club: "Borussia Dortmund", value: "€28M" },
      { name: "Oliver Baumann", club: "Hoffenheim", value: "€3M" },
      { name: "Robin Koch", club: "Eintracht Frankfurt", value: "€10M" },
      { name: "Emre Can", club: "Borussia Dortmund", value: "€10M" },
      { name: "Thomas Müller", club: "Bayern Munich", value: "€10M" },
      { name: "Tim Kleindienst", club: "Borussia Mönchengladbach", value: "€12M" },
    ],
    spain: [
      { name: "Unai Simón", club: "Athletic Bilbao", value: "€30M" },
      { name: "Dani Carvajal", club: "Real Madrid", value: "€20M" },
      { name: "Aymeric Laporte", club: "Al-Nassr", value: "€20M" },
      { name: "Robin Le Normand", club: "Atlético Madrid", value: "€35M" },
      { name: "Marc Cucurella", club: "Chelsea", value: "€35M" },
      { name: "Rodri", club: "Manchester City", value: "€130M" },
      { name: "Pedri", club: "Barcelona", value: "€100M" },
      { name: "Fabián Ruiz", club: "PSG", value: "€45M" },
      { name: "Dani Olmo", club: "Barcelona", value: "€60M" },
      { name: "Álvaro Morata", club: "AC Milan", value: "€15M" },
      { name: "Lamine Yamal", club: "Barcelona", value: "€180M" },
      { name: "Nico Williams", club: "Athletic Bilbao", value: "€70M" },
      { name: "David Raya", club: "Arsenal", value: "€35M" },
      { name: "Nacho", club: "Al-Qadsiah", value: "€3M" },
      { name: "Jesús Navas", club: "Sevilla", value: "€2M" },
      { name: "Mikel Merino", club: "Arsenal", value: "€40M" },
      { name: "Alejandro Baena", club: "Villarreal", value: "€40M" },
      { name: "Ferran Torres", club: "Barcelona", value: "€30M" },
      { name: "Pau Cubarsí", club: "Barcelona", value: "€60M" },
      { name: "Martín Zubimendi", club: "Real Sociedad", value: "€55M" },
      { name: "Joselu", club: "Al-Gharafa", value: "€5M" },
      { name: "Álex Remiro", club: "Real Sociedad", value: "€15M" },
      { name: "Grimaldo", club: "Bayer Leverkusen", value: "€40M" },
      { name: "Gavi", club: "Barcelona", value: "€90M" },
      { name: "Ayoze Pérez", club: "Villarreal", value: "€18M" },
      { name: "Mikel Oyarzabal", club: "Real Sociedad", value: "€35M" },
    ],
    portugal: [
      { name: "Diogo Costa", club: "Porto", value: "€45M" },
      { name: "Diogo Dalot", club: "Manchester United", value: "€40M" },
      { name: "Rúben Dias", club: "Manchester City", value: "€75M" },
      { name: "Pepe", club: "Retired", value: "€1M" },
      { name: "Nuno Mendes", club: "PSG", value: "€65M" },
      { name: "Vitinha", club: "PSG", value: "€75M" },
      { name: "João Palhinha", club: "Bayern Munich", value: "€45M" },
      { name: "Bruno Fernandes", club: "Manchester United", value: "€65M" },
      { name: "Bernardo Silva", club: "Manchester City", value: "€80M" },
      { name: "Cristiano Ronaldo", club: "Al-Nassr", value: "€15M" },
      { name: "Rafael Leão", club: "AC Milan", value: "€80M" },
      { name: "Gonçalo Ramos", club: "PSG", value: "€50M" },
      { name: "Rui Patrício", club: "Roma", value: "€3M" },
      { name: "João Cancelo", club: "Al-Hilal", value: "€35M" },
      { name: "António Silva", club: "Benfica", value: "€45M" },
      { name: "João Neves", club: "PSG", value: "€80M" },
      { name: "Renato Sanches", club: "Benfica", value: "€8M" },
      { name: "Pedro Neto", club: "Chelsea", value: "€55M" },
      { name: "Gonçalo Inácio", club: "Sporting CP", value: "€45M" },
      { name: "Rúben Neves", club: "Al-Hilal", value: "€30M" },
      { name: "Diogo Jota", club: "Liverpool", value: "€55M" },
      { name: "José Sá", club: "Wolves", value: "€12M" },
      { name: "Nélson Semedo", club: "Wolves", value: "€15M" },
      { name: "Otávio", club: "Al-Nassr", value: "€15M" },
      { name: "Francisco Conceição", club: "Juventus", value: "€30M" },
      { name: "João Félix", club: "Chelsea", value: "€30M" },
    ],
    netherlands: [
      { name: "Bart Verbruggen", club: "Brighton", value: "€28M" },
      { name: "Denzel Dumfries", club: "Inter Milan", value: "€28M" },
      { name: "Virgil van Dijk", club: "Liverpool", value: "€35M" },
      { name: "Nathan Aké", club: "Manchester City", value: "€40M" },
      { name: "Jurriën Timber", club: "Arsenal", value: "€45M" },
      { name: "Frenkie de Jong", club: "Barcelona", value: "€60M" },
      { name: "Ryan Gravenberch", club: "Liverpool", value: "€50M" },
      { name: "Tijjani Reijnders", club: "AC Milan", value: "€50M" },
      { name: "Xavi Simons", club: "RB Leipzig", value: "€80M" },
      { name: "Memphis Depay", club: "Corinthians", value: "€6M" },
      { name: "Cody Gakpo", club: "Liverpool", value: "€60M" },
      { name: "Donyell Malen", club: "Aston Villa", value: "€45M" },
      { name: "Justin Bijlow", club: "Feyenoord", value: "€10M" },
      { name: "Matthijs de Ligt", club: "Manchester United", value: "€55M" },
      { name: "Micky van de Ven", club: "Tottenham", value: "€55M" },
      { name: "Marten de Roon", club: "Atalanta", value: "€6M" },
      { name: "Teun Koopmeiners", club: "Juventus", value: "€50M" },
      { name: "Steven Bergwijn", club: "Al-Ittihad", value: "€12M" },
      { name: "Stefan de Vrij", club: "Inter Milan", value: "€8M" },
      { name: "Jeremie Frimpong", club: "Bayer Leverkusen", value: "€45M" },
      { name: "Brian Brobbey", club: "Ajax", value: "€30M" },
      { name: "Mark Flekken", club: "Brentford", value: "€8M" },
      { name: "Ian Maatsen", club: "Aston Villa", value: "€35M" },
      { name: "Quinten Timber", club: "Feyenoord", value: "€22M" },
      { name: "Wout Weghorst", club: "Ajax", value: "€6M" },
      { name: "Joshua Zirkzee", club: "Manchester United", value: "€40M" },
    ],
    italy: [
      { name: "Gianluigi Donnarumma", club: "PSG", value: "€40M" },
      { name: "Giovanni Di Lorenzo", club: "Napoli", value: "€25M" },
      { name: "Alessandro Bastoni", club: "Inter Milan", value: "€75M" },
      { name: "Riccardo Calafiori", club: "Arsenal", value: "€55M" },
      { name: "Federico Dimarco", club: "Inter Milan", value: "€40M" },
      { name: "Nicolò Barella", club: "Inter Milan", value: "€80M" },
      { name: "Sandro Tonali", club: "Newcastle", value: "€50M" },
      { name: "Davide Frattesi", club: "Inter Milan", value: "€40M" },
      { name: "Lorenzo Pellegrini", club: "Roma", value: "€28M" },
      { name: "Federico Chiesa", club: "Liverpool", value: "€35M" },
      { name: "Gianluca Scamacca", club: "Atalanta", value: "€40M" },
      { name: "Mateo Retegui", club: "Atalanta", value: "€30M" },
      { name: "Alex Meret", club: "Napoli", value: "€12M" },
      { name: "Andrea Cambiaso", club: "Juventus", value: "€40M" },
      { name: "Alessandro Buongiorno", club: "Napoli", value: "€35M" },
      { name: "Manuel Locatelli", club: "Juventus", value: "€20M" },
      { name: "Samuele Ricci", club: "Torino", value: "€25M" },
      { name: "Giacomo Raspadori", club: "Napoli", value: "€28M" },
      { name: "Matteo Darmian", club: "Inter Milan", value: "€5M" },
      { name: "Bryan Cristante", club: "Roma", value: "€18M" },
      { name: "Stephan El Shaarawy", club: "Roma", value: "€6M" },
      { name: "Guglielmo Vicario", club: "Tottenham", value: "€35M" },
      { name: "Raoul Bellanova", club: "Atalanta", value: "€22M" },
      { name: "Nicolò Fagioli", club: "Juventus", value: "€20M" },
      { name: "Moise Kean", club: "Fiorentina", value: "€25M" },
      { name: "Daniel Maldini", club: "Monza", value: "€8M" },
    ],
    usa: [
      { name: "Matt Turner", club: "Crystal Palace", value: "€6M" },
      { name: "Sergiño Dest", club: "PSV", value: "€12M" },
      { name: "Chris Richards", club: "Crystal Palace", value: "€15M" },
      { name: "Tim Ream", club: "Charlotte FC", value: "€2M" },
      { name: "Antonee Robinson", club: "Fulham", value: "€25M" },
      { name: "Tyler Adams", club: "Bournemouth", value: "€18M" },
      { name: "Weston McKennie", club: "Juventus", value: "€22M" },
      { name: "Giovanni Reyna", club: "Borussia Dortmund", value: "€25M" },
      { name: "Christian Pulisic", club: "AC Milan", value: "€45M" },
      { name: "Folarin Balogun", club: "Monaco", value: "€35M" },
      { name: "Timothy Weah", club: "Juventus", value: "€18M" },
      { name: "Ricardo Pepi", club: "PSV", value: "€15M" },
      { name: "Ethan Horvath", club: "Cardiff City", value: "€2M" },
      { name: "Joe Scally", club: "Borussia Mönchengladbach", value: "€15M" },
      { name: "Mark McKenzie", club: "Toulouse", value: "€5M" },
      { name: "Yunus Musah", club: "AC Milan", value: "€25M" },
      { name: "Johnny Cardoso", club: "Real Betis", value: "€20M" },
      { name: "Brenden Aaronson", club: "Leeds United", value: "€22M" },
      { name: "Cameron Carter-Vickers", club: "Celtic", value: "€12M" },
      { name: "Malik Tillman", club: "PSV", value: "€18M" },
      { name: "Haji Wright", club: "Coventry City", value: "€5M" },
      { name: "Zack Steffen", club: "Colorado Rapids", value: "€3M" },
      { name: "Miles Robinson", club: "FC Cincinnati", value: "€5M" },
      { name: "Luca de la Torre", club: "Celta Vigo", value: "€4M" },
      { name: "Josh Sargent", club: "Norwich City", value: "€12M" },
      { name: "Brandon Vazquez", club: "Monterrey", value: "€5M" },
    ],
    mexico: [
      { name: "Guillermo Ochoa", club: "AVS", value: "€1M" },
      { name: "Jorge Sánchez", club: "Porto", value: "€5M" },
      { name: "César Montes", club: "Almería", value: "€4M" },
      { name: "Johan Vásquez", club: "Genoa", value: "€8M" },
      { name: "Jesús Gallardo", club: "Toluca", value: "€3M" },
      { name: "Edson Álvarez", club: "West Ham", value: "€35M" },
      { name: "Luis Romo", club: "Monterrey", value: "€6M" },
      { name: "Orbelín Pineda", club: "AEK Athens", value: "€6M" },
      { name: "Diego Lainez", club: "Tigres", value: "€5M" },
      { name: "Santiago Giménez", club: "Feyenoord", value: "€40M" },
      { name: "Hirving Lozano", club: "PSV", value: "€15M" },
      { name: "Julián Quiñones", club: "América", value: "€8M" },
      { name: "Luis Malagón", club: "América", value: "€3M" },
      { name: "Kevin Álvarez", club: "Pachuca", value: "€4M" },
      { name: "Israel Reyes", club: "América", value: "€5M" },
      { name: "Carlos Rodríguez", club: "Cruz Azul", value: "€5M" },
      { name: "Sebastián Córdova", club: "Tigres", value: "€5M" },
      { name: "Alexis Vega", club: "Toluca", value: "€6M" },
      { name: "Gerardo Arteaga", club: "Monterrey", value: "€5M" },
      { name: "Luis Chávez", club: "Dinamo Moscow", value: "€4M" },
      { name: "Henry Martín", club: "América", value: "€5M" },
      { name: "Raúl Rangel", club: "Guadalajara", value: "€2M" },
      { name: "Érik Lira", club: "Cruz Azul", value: "€3M" },
      { name: "Marcel Ruiz", club: "Toluca", value: "€3M" },
      { name: "Uriel Antuna", club: "Cruz Azul", value: "€5M" },
      { name: "Guillermo Martínez", club: "Pumas", value: "€2M" },
    ],
    canada: [
      { name: "Maxime Crépeau", club: "Portland Timbers", value: "€3M" },
      { name: "Alistair Johnston", club: "Celtic", value: "€12M" },
      { name: "Moise Bombito", club: "Colorado Rapids", value: "€5M" },
      { name: "Derek Cornelius", club: "Malmö", value: "€3M" },
      { name: "Alphonso Davies", club: "Bayern Munich", value: "€70M" },
      { name: "Stephen Eustáquio", club: "Porto", value: "€12M" },
      { name: "Ismaël Koné", club: "Marseille", value: "€15M" },
      { name: "Jonathan David", club: "Lille", value: "€55M" },
      { name: "Tajon Buchanan", club: "Villarreal", value: "€12M" },
      { name: "Cyle Larin", club: "Real Valladolid", value: "€5M" },
      { name: "Jonathan Osorio", club: "Toronto FC", value: "€3M" },
      { name: "Liam Millar", club: "Preston", value: "€3M" },
      { name: "Dayne St. Clair", club: "Minnesota United", value: "€3M" },
      { name: "Richie Laryea", club: "Toronto FC", value: "€2M" },
      { name: "Kamal Miller", club: "Portland Timbers", value: "€3M" },
      { name: "Samuel Piette", club: "CF Montréal", value: "€2M" },
      { name: "Mark-Anthony Kaye", club: "Real Salt Lake", value: "€2M" },
      { name: "Junior Hoilett", club: "Aberdeen", value: "€1M" },
      { name: "Scott Kennedy", club: "Holstein Kiel", value: "€2M" },
      { name: "Mathieu Choinière", club: "CF Montréal", value: "€2M" },
      { name: "Jacob Shaffelburg", club: "Nashville SC", value: "€2M" },
      { name: "Thomas McGill", club: "Vancouver Whitecaps", value: "€500K" },
      { name: "Dominique Badji", club: "Ottawa", value: "€500K" },
      { name: "Ali Ahmed", club: "Lillestrøm", value: "€1M" },
      { name: "Tani Oluwaseyi", club: "Minnesota United", value: "€2M" },
      { name: "Charles-Andreas Brym", club: "Ottawa", value: "€500K" },
    ],
  };

  const heights = ["175 cm", "178 cm", "180 cm", "182 cm", "183 cm", "185 cm", "186 cm", "188 cm", "190 cm", "192 cm"];
  const weights = ["70 kg", "72 kg", "75 kg", "78 kg", "80 kg", "82 kg", "85 kg", "88 kg", "90 kg"];
  const feet = ["Right", "Left", "Both"];
  
  const nationalPlayers = playersByNation[nationId] || [];
  
  return nationalPlayers.map((p, index) => ({
    id: `${nationId}-${index + 1}`,
    fullName: p.name,
    position: positions[index % positions.length],
    club: p.club,
    height: heights[index % heights.length],
    weight: weights[index % weights.length],
    strongFoot: feet[index % 3],
    marketValue: p.value,
    imageUrl: `https://ui-avatars.com/api/?name=${encodeURIComponent(p.name)}&background=random&size=200&bold=true`,
  }));
}

export const nations: Nation[] = [
  // Host Nations
  {
    id: "usa",
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    confederation: "CONCACAF",
    totalSquadValue: "€380M",
    jerseyColors: { primary: "#002868", secondary: "#FFFFFF", accent: "#BF0A30" },
    players: generatePlayers("usa", "United States"),
  },
  {
    id: "mexico",
    name: "Mexico",
    code: "MX",
    flag: "🇲🇽",
    confederation: "CONCACAF",
    totalSquadValue: "€185M",
    jerseyColors: { primary: "#006847", secondary: "#FFFFFF", accent: "#CE1126" },
    players: generatePlayers("mexico", "Mexico"),
  },
  {
    id: "canada",
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    confederation: "CONCACAF",
    totalSquadValue: "€215M",
    jerseyColors: { primary: "#FF0000", secondary: "#FFFFFF", accent: "#000000" },
    players: generatePlayers("canada", "Canada"),
  },
  // UEFA
  {
    id: "argentina",
    name: "Argentina",
    code: "AR",
    flag: "🇦🇷",
    confederation: "CONMEBOL",
    totalSquadValue: "€780M",
    jerseyColors: { primary: "#75AADB", secondary: "#FFFFFF", accent: "#F6B40E" },
    players: generatePlayers("argentina", "Argentina"),
  },
  {
    id: "brazil",
    name: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    confederation: "CONMEBOL",
    totalSquadValue: "€1.1B",
    jerseyColors: { primary: "#FFDF00", secondary: "#009C3B", accent: "#002776" },
    players: generatePlayers("brazil", "Brazil"),
  },
  {
    id: "france",
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    confederation: "UEFA",
    totalSquadValue: "€1.2B",
    jerseyColors: { primary: "#002395", secondary: "#FFFFFF", accent: "#ED2939" },
    players: generatePlayers("france", "France"),
  },
  {
    id: "england",
    name: "England",
    code: "GB-ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    confederation: "UEFA",
    totalSquadValue: "€1.5B",
    jerseyColors: { primary: "#FFFFFF", secondary: "#002366", accent: "#CF081F" },
    players: generatePlayers("england", "England"),
  },
  {
    id: "germany",
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    confederation: "UEFA",
    totalSquadValue: "€850M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#000000", accent: "#DD0000" },
    players: generatePlayers("germany", "Germany"),
  },
  {
    id: "spain",
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    confederation: "UEFA",
    totalSquadValue: "€1.1B",
    jerseyColors: { primary: "#AA151B", secondary: "#F1BF00", accent: "#FFFFFF" },
    players: generatePlayers("spain", "Spain"),
  },
  {
    id: "portugal",
    name: "Portugal",
    code: "PT",
    flag: "🇵🇹",
    confederation: "UEFA",
    totalSquadValue: "€920M",
    jerseyColors: { primary: "#FF0000", secondary: "#006600", accent: "#FFCC00" },
    players: generatePlayers("portugal", "Portugal"),
  },
  {
    id: "netherlands",
    name: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
    confederation: "UEFA",
    totalSquadValue: "€780M",
    jerseyColors: { primary: "#FF6600", secondary: "#FFFFFF", accent: "#21468B" },
    players: generatePlayers("netherlands", "Netherlands"),
  },
  {
    id: "italy",
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    confederation: "UEFA",
    totalSquadValue: "€680M",
    jerseyColors: { primary: "#0066CC", secondary: "#FFFFFF", accent: "#009246" },
    players: generatePlayers("italy", "Italy"),
  },
  {
    id: "belgium",
    name: "Belgium",
    code: "BE",
    flag: "🇧🇪",
    confederation: "UEFA",
    totalSquadValue: "€520M",
    jerseyColors: { primary: "#FF0000", secondary: "#000000", accent: "#FDDA24" },
    players: [],
  },
  {
    id: "croatia",
    name: "Croatia",
    code: "HR",
    flag: "🇭🇷",
    confederation: "UEFA",
    totalSquadValue: "€380M",
    jerseyColors: { primary: "#FF0000", secondary: "#FFFFFF", accent: "#171796" },
    players: [],
  },
  {
    id: "denmark",
    name: "Denmark",
    code: "DK",
    flag: "🇩🇰",
    confederation: "UEFA",
    totalSquadValue: "€350M",
    jerseyColors: { primary: "#C60C30", secondary: "#FFFFFF", accent: "#C60C30" },
    players: [],
  },
  {
    id: "switzerland",
    name: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
    confederation: "UEFA",
    totalSquadValue: "€280M",
    jerseyColors: { primary: "#FF0000", secondary: "#FFFFFF", accent: "#FF0000" },
    players: [],
  },
  {
    id: "austria",
    name: "Austria",
    code: "AT",
    flag: "🇦🇹",
    confederation: "UEFA",
    totalSquadValue: "€250M",
    jerseyColors: { primary: "#ED2939", secondary: "#FFFFFF", accent: "#ED2939" },
    players: [],
  },
  {
    id: "serbia",
    name: "Serbia",
    code: "RS",
    flag: "🇷🇸",
    confederation: "UEFA",
    totalSquadValue: "€320M",
    jerseyColors: { primary: "#C6363C", secondary: "#0C4076", accent: "#FFFFFF" },
    players: [],
  },
  {
    id: "poland",
    name: "Poland",
    code: "PL",
    flag: "🇵🇱",
    confederation: "UEFA",
    totalSquadValue: "€220M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#DC143C", accent: "#FFFFFF" },
    players: [],
  },
  // CONMEBOL
  {
    id: "colombia",
    name: "Colombia",
    code: "CO",
    flag: "🇨🇴",
    confederation: "CONMEBOL",
    totalSquadValue: "€380M",
    jerseyColors: { primary: "#FCD116", secondary: "#003893", accent: "#CE1126" },
    players: [],
  },
  {
    id: "uruguay",
    name: "Uruguay",
    code: "UY",
    flag: "🇺🇾",
    confederation: "CONMEBOL",
    totalSquadValue: "€450M",
    jerseyColors: { primary: "#7FB5B5", secondary: "#001489", accent: "#FFFFFF" },
    players: [],
  },
  {
    id: "ecuador",
    name: "Ecuador",
    code: "EC",
    flag: "🇪🇨",
    confederation: "CONMEBOL",
    totalSquadValue: "€180M",
    jerseyColors: { primary: "#FFD100", secondary: "#0038A8", accent: "#CE1126" },
    players: [],
  },
  {
    id: "chile",
    name: "Chile",
    code: "CL",
    flag: "🇨🇱",
    confederation: "CONMEBOL",
    totalSquadValue: "€120M",
    jerseyColors: { primary: "#D52B1E", secondary: "#0039A6", accent: "#FFFFFF" },
    players: [],
  },
  {
    id: "paraguay",
    name: "Paraguay",
    code: "PY",
    flag: "🇵🇾",
    confederation: "CONMEBOL",
    totalSquadValue: "€85M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#DA121A", accent: "#0038A8" },
    players: [],
  },
  {
    id: "venezuela",
    name: "Venezuela",
    code: "VE",
    flag: "🇻🇪",
    confederation: "CONMEBOL",
    totalSquadValue: "€95M",
    jerseyColors: { primary: "#800020", secondary: "#FFFFFF", accent: "#CF142B" },
    players: [],
  },
  // AFC
  {
    id: "japan",
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    confederation: "AFC",
    totalSquadValue: "€380M",
    jerseyColors: { primary: "#000080", secondary: "#FFFFFF", accent: "#BC002D" },
    players: [],
  },
  {
    id: "south-korea",
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    confederation: "AFC",
    totalSquadValue: "€220M",
    jerseyColors: { primary: "#C60C30", secondary: "#003478", accent: "#FFFFFF" },
    players: [],
  },
  {
    id: "australia",
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    confederation: "AFC",
    totalSquadValue: "€85M",
    jerseyColors: { primary: "#FFCD00", secondary: "#00843D", accent: "#00008B" },
    players: [],
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
    confederation: "AFC",
    totalSquadValue: "€35M",
    jerseyColors: { primary: "#006C35", secondary: "#FFFFFF", accent: "#006C35" },
    players: [],
  },
  {
    id: "iran",
    name: "Iran",
    code: "IR",
    flag: "🇮🇷",
    confederation: "AFC",
    totalSquadValue: "€65M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#239F40", accent: "#DA0000" },
    players: [],
  },
  {
    id: "qatar",
    name: "Qatar",
    code: "QA",
    flag: "🇶🇦",
    confederation: "AFC",
    totalSquadValue: "€25M",
    jerseyColors: { primary: "#8A1538", secondary: "#FFFFFF", accent: "#8A1538" },
    players: [],
  },
  // CAF
  {
    id: "morocco",
    name: "Morocco",
    code: "MA",
    flag: "🇲🇦",
    confederation: "CAF",
    totalSquadValue: "€350M",
    jerseyColors: { primary: "#C1272D", secondary: "#006233", accent: "#FFFFFF" },
    players: [],
  },
  {
    id: "senegal",
    name: "Senegal",
    code: "SN",
    flag: "🇸🇳",
    confederation: "CAF",
    totalSquadValue: "€280M",
    jerseyColors: { primary: "#00853F", secondary: "#FDEF42", accent: "#E31B23" },
    players: [],
  },
  {
    id: "cameroon",
    name: "Cameroon",
    code: "CM",
    flag: "🇨🇲",
    confederation: "CAF",
    totalSquadValue: "€180M",
    jerseyColors: { primary: "#007A5E", secondary: "#CE1126", accent: "#FCD116" },
    players: [],
  },
  {
    id: "nigeria",
    name: "Nigeria",
    code: "NG",
    flag: "🇳🇬",
    confederation: "CAF",
    totalSquadValue: "€250M",
    jerseyColors: { primary: "#008751", secondary: "#FFFFFF", accent: "#008751" },
    players: [],
  },
  {
    id: "egypt",
    name: "Egypt",
    code: "EG",
    flag: "🇪🇬",
    confederation: "CAF",
    totalSquadValue: "€180M",
    jerseyColors: { primary: "#C8102E", secondary: "#FFFFFF", accent: "#000000" },
    players: [],
  },
  {
    id: "algeria",
    name: "Algeria",
    code: "DZ",
    flag: "🇩🇿",
    confederation: "CAF",
    totalSquadValue: "€150M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#006233", accent: "#D21034" },
    players: [],
  },
  // OFC
  {
    id: "new-zealand",
    name: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
    confederation: "OFC",
    totalSquadValue: "€25M",
    jerseyColors: { primary: "#FFFFFF", secondary: "#000000", accent: "#00247D" },
    players: [],
  },
];

// Fill in empty player arrays with generated data
nations.forEach(nation => {
  if (nation.players.length === 0) {
    nation.players = Array.from({ length: 26 }, (_, i) => ({
      id: `${nation.id}-${i + 1}`,
      fullName: `Player ${i + 1}`,
      position: ["Goalkeeper", "Defender", "Defender", "Defender", "Defender", "Midfielder", "Midfielder", "Midfielder", "Midfielder", "Forward", "Forward", "Forward"][i % 12],
      club: "Club TBA",
      height: `${175 + (i % 20)} cm`,
      weight: `${70 + (i % 25)} kg`,
      strongFoot: ["Right", "Left", "Both"][i % 3],
      marketValue: "€10M",
      imageUrl: `https://ui-avatars.com/api/?name=Player+${i + 1}&background=random&size=200&bold=true`,
    }));
  }
});
